[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.22"

[features]
seeds = false
skip-lint = false

[programs.localnet]
borgpad = "bpadbLrS3Mw2e1EDSEnYzYpNwAQgJQXXHkT57D4TTJ4"

[provider]
cluster = "localnet"
wallet = "tests/helpers/local_deployer.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/projectRefund.ts"

init-script = "yarn run ts-node scripts/initialize.ts"

[[test.genesis]]
address = "bpadbLrS3Mw2e1EDSEnYzYpNwAQgJQXXHkT57D4TTJ4"
program = "target/deploy/borgpad.so"
upgradeable = true
